Repository slamapp/client, pull requests merged in 2022-02, with the labels that each got.

#73 클라이언트 / 서버의 width값이 다른 에러가 나오는 error가 나오는 문제 해결 및 Paragraph 변수명과 성능최적화
  src/components/base/Skeleton/Paragraph.tsx
  src/components/domain/Favorites/index.tsx
Labels: 버그, 개선, 리팩토링

#75 폰트 cors문제와 safari 폰트 및 크로스브라우징 문제 해결
  next.config.js
  src/components/domain/CourtItem/style.tsx
  src/components/domain/NoItemMessage/index.tsx
  src/pages/_document.tsx
  src/pages/courts/[courtId]/[date].tsx
Labels: 버그

#77 Avatar와 LinkAvatar을 Profile로 리팩토링 및 FollowListItem이름을 명확하게 하기
  src/components/domain/LinkAvatar/index.tsx
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/ProfileAvatar/index.tsx
  src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/UserListItem/index.tsx
  src/components/domain/index.ts
  src/domainTypes/tobe/common.ts
  src/pages/user/[userId]/following.tsx
  src/service/reservationApi/type.ts
Labels: 개선, 리팩토링

#78 Google Analytics 4 추가
  package.json
  src/contexts/AnalyticsProvider/context.ts
  src/contexts/AnalyticsProvider/handle.ts
  src/contexts/AnalyticsProvider/hooks.ts
  src/contexts/AnalyticsProvider/index.tsx
  src/contexts/Providers.tsx
  yarn.lock
Labels: 기능

#67 예약 컨펌 모달 스텝 모달로 변경
  src/components/base/Button/index.tsx
  src/components/domain/Modal/style.tsx
  src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/index.ts
  src/contexts/ReservationProvider/context.ts
  src/contexts/ReservationProvider/index.tsx
  src/contexts/ReservationProvider/reducer.ts
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/pages/user/menu/index.tsx
  src/utils/date.ts
Labels: 개선, 기능

#81 ShareBinder가 component를 받아 모든 공유상황(코트 / 유저 / 코트채팅방 / 유저채팅방)에 대해 로직을 주입하는 HOC 제작
  package.json
  src/UtilRoute/index.tsx
  src/components/base/Button/index.tsx
  src/components/base/IconButton/icons/index.tsx
  src/components/base/IconButton/index.tsx
  src/components/domain/CourtItem/Share.tsx
  src/components/domain/CourtItem/ShareButton.tsx
  src/components/domain/CourtItem/index.tsx
  src/components/domain/FavoriteList/index.tsx
  src/components/domain/KakaoLogin/index.tsx
  src/components/domain/KakaoLogin/loadSdk.ts
  src/components/domain/KakaoLogin/types.ts
  src/components/domain/KakaoMap/CurrentLocationButton.tsx
  src/components/domain/ReservationItem/index.tsx
  src/components/domain/index.ts
  src/domainTypes/tobe/chatroom.ts
  src/domainTypes/tobe/index.ts
  src/hocs/index.ts
  src/hocs/withRouteGuard/index.tsx
  src/hocs/withShareClick/index.tsx
  src/hocs/withShareClick/sendKakaoLink.ts
  src/hocs/withShareClick/types.ts
  src/hooks/index.ts
  src/hooks/useKakao/index.ts
  src/hooks/useKakao/types.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/chat/courts/[courtId]/index.tsx
  src/pages/chat/index.tsx
  src/pages/chat/users/[userId]/index.tsx
  src/pages/courts/create.tsx
  src/pages/courts/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/notifications/index.tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/follower.tsx
  src/pages/user/[userId]/following.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/pages/user/menu/index.tsx
  tsconfig.json
  yarn.lock
Labels: 개선, 리팩토링, 기능

#86 NavigationContext 타이핑
  src/components/domain/BottomNavigtion/NavIcon/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/contexts/NavigationProvider/actionTypes.ts
  src/contexts/NavigationProvider/context.ts
  src/contexts/NavigationProvider/index.tsx
  src/contexts/NavigationProvider/reducer.ts
  src/contexts/NavigationProvider/types.ts
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/activity/index.tsx
  src/pages/admin/newcourts.tsx
  src/pages/chat/courts/[courtId]/index.tsx
  src/pages/chat/index.tsx
  src/pages/chat/users/[userId]/index.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/create.tsx
  src/pages/courts/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/notifications/index.tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/follower.tsx
  src/pages/user/[userId]/following.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/pages/user/menu/index.tsx
Labels: 개선, 리팩토링

#47 채팅방 리스트 페이지
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/CourtItem/ChatLink.tsx
  src/components/domain/FavoriteList/index.tsx
  src/components/domain/ReservationItem/index.tsx
  src/pages/chat/[chatroomId]/index.tsx
  src/pages/chat/courts/[courtId]/index.tsx
  src/pages/chat/list/index.tsx
  src/pages/chat/users/[userId]/index.tsx
  src/pages/courts/index.tsx
Labels: 기능

#92 userApi 타이핑 및 프로필 수정 페이지 리팩토링
  src/components/base/Input/index.tsx
  src/components/base/Upload/index.tsx
  src/components/base/index.ts
  src/components/domain/CourtItem/FavoritesToggle.tsx
  src/components/domain/NewCourtItem/index.tsx
  src/components/domain/NewCourtItem/types.ts
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/UserInfoPicker/PositionsPicker.tsx
  src/components/domain/ValidationNoticeBar/index.tsx
  src/components/domain/index.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/domainTypes/newCourts.ts
  src/domainTypes/tobe/newCourt.ts
  src/hooks/useForm.ts
  src/pages/admin/newcourts.tsx
  src/pages/courts/create.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/service/managementApi/index.ts
  src/service/managementApi/type.ts
  src/service/userApi/type.ts
Labels: 버그, 개선, 리팩토링
