Repository slamapp/client, pull requests merged in 2022-01, with the labels that each got.

#49 yarn dev 명령어 실행 시 터미널 콘솔에 뜨는 익명 화살표 함수 warning, referenceerror 에러 해결
  .commitlintrc.json
  package.json
  src/components/domain/KakaoLogin/loadSdk.ts
  src/hooks/domain/useLocalToken.ts
  src/hooks/useLocalStorage.ts
  yarn.lock
Labels: 버그

#56 reservation context api 적용, 에러 수정
  src/components/domain/CourtItem/Datetime.tsx
  src/components/domain/ReservationModalContent/BlockStatus.tsx
  src/components/domain/ReservationModalContent/ExistedReservation.tsx
  src/components/domain/ReservationModalContent/SelectedRange.tsx
  src/components/domain/TimeTable/TimeBlockUnits/TimeBlockUnit.tsx
  src/components/domain/TimeTable/index.tsx
  src/components/domain/TimeTable/type.ts
  src/contexts/Providers.tsx
  src/contexts/ReservationProvider/actionTypes.ts
  src/contexts/ReservationProvider/context.ts
  src/contexts/ReservationProvider/hook.ts
  src/contexts/ReservationProvider/index.tsx
  src/contexts/ReservationProvider/reducer.ts
  src/contexts/hooks.ts
  src/contexts/index.ts
  src/pages/courts/[courtId]/[date].tsx
  src/utils/date.ts
Labels: 버그, 개선

#53 API타이핑을 위한 디렉토리 구조 리팩토링
  src/components/domain/Favorites/index.tsx
  src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
  src/contexts/AuthProvider/index.tsx
  src/pages/admin/newcourts.tsx
  src/pages/courts/[courtId]/[date].tsx
  src/pages/courts/index.tsx
  src/pages/reservations/index.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/service/courtApi.ts
  src/service/courtApi/index.ts
  src/service/courtApi/type.ts
  src/service/favoriteApi.ts
  src/service/favoriteApi/index.ts
  src/service/favoriteApi/type.ts
  src/service/fetcher/interceptor/getConfig.ts
  src/service/managementApi.ts
  src/service/managementApi/index.ts
  src/service/managementApi/type.ts
  src/service/notificationApi/index.ts
  src/service/notificationApi/type.ts
  src/service/reservationApi/index.ts
  src/service/reservationApi/type.ts
  src/service/socketApi/index.ts
  src/service/socketApi/type.ts
  src/service/type.ts
  src/service/userApi.ts
  src/service/userApi/index.ts
  src/service/userApi/type.ts
Labels: 리팩토링

#51 함께하는 사람 출력 시 자기 자신도 출력
  src/components/domain/FollowListItem/index.tsx
  src/components/domain/LinkAvatar/index.tsx
  src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
Labels: 기능

#55 프로필 이미지 편집 기능 구현
  src/components/base/Upload/index.tsx
  src/components/domain/ProfileForm/index.tsx
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/pages/user/edit/index.tsx
  src/service/fetcher/interceptor/getConfig.ts
  src/service/userApi/index.ts
  src/service/userApi/type.ts
  src/utils/appendImageFileToFormData.ts
  src/utils/index.ts
Labels: 기능

#60 유저페이지 타이틀이 undefined로 표시되는 문제 해결
  src/pages/user/[userId]/index.tsx
Labels: 버그

#63 접근성과 검색엔진최적화를 위한 Avatar와 LinkAvatar에 기본 alt속성 추가
  src/components/base/Avatar/index.tsx
  src/components/domain/LinkAvatar/index.tsx
Labels: 개선

#61 (긴급🚨 ) 변경된 API에 맞게 유저 관련 타이핑, 수정 / API request 최적화
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/domainTypes/tobe/user.ts
  src/pages/user/[userId]/index.tsx
  src/service/userApi/type.ts
Labels: 버그, 개선, 리팩토링

#70 (우선순위🚨) 변경된 API의 객체 id가 number | string일 수 있는 경우 대응
  src/domainTypes/tobe/chatroom.ts
  src/domainTypes/tobe/common.ts
  src/domainTypes/tobe/follow.ts
  src/domainTypes/tobe/loudspeaker.ts
  src/domainTypes/tobe/newCourt.ts
  src/domainTypes/tobe/notification.ts
  src/domainTypes/tobe/reservation.ts
  src/pages/user/edit/index.tsx
Labels: 개선

#71 AuthContext관련 명확한 타이핑 및 tobe/type들 적용
  src/components/base/Avatar/index.tsx
  src/components/domain/BottomNavigtion/index.tsx
  src/components/domain/NotificationList/NotificationItem/index.tsx
  src/components/domain/ProfileForm/index.tsx
  src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
  src/components/domain/TopNavigation/index.tsx
  src/components/domain/UserInfoPicker/PositionsPicker.tsx
  src/components/domain/UserInfoPicker/ProficiencyPicker.tsx
  src/constants/index.ts
  src/contexts/AuthProvider/actionTypes.ts
  src/contexts/AuthProvider/context.ts
  src/contexts/AuthProvider/index.tsx
  src/contexts/AuthProvider/reducer.ts
  src/contexts/ReservationProvider/index.tsx
  src/contexts/SocketProvider/useStomp/index.ts
  src/contexts/type.ts
  src/domainTypes/index.ts
  src/domainTypes/notifications.ts
  src/domainTypes/tobe/user.ts
  src/domainTypes/users.ts
  src/pages/user/[userId]/following.tsx
  src/pages/user/[userId]/index.tsx
  src/pages/user/edit/index.tsx
  src/service/notificationApi/type.ts
  src/service/userApi/index.ts
  src/service/userApi/type.ts
  src/utils/userInfo.ts
  tsconfig.json
Labels: 개선, 리팩토링
